### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by jeromecoupe** [jeromecoupe/iad_eleventy_introduction#2]
- [x] translate content to EN
- [x] get a trusted person to proofread
- [x] update Readme to point to both versions

**Comment by zachleat** [comment]
subscribed

**Comment by jeromecoupe** [comment]
No pressure ;o)

**Comment by jeromecoupe** [comment]
Hey @zachleat, so cool to see you here! Now done with the first pass at the EN translation. Feel free to have a look and give feedback on the structure and general flow of things or to report gross mistakes.
